In [8]:
%matplotlib inline
import pylab as pl
import numpy as np
import pandas as pd

#Read data

X_train = []
samples_x_train = []

f = open("genotypes.csv","r")

for i,line in enumerate(f):
    if(i == 0):
        continue
    
    sv = line.strip().split(",")
    samples_x_train.append(sv[0])
    
    row = []
    for element in sv[1:]:
        row.append(element)
    X_train.append(row)
    
f.close()

X_train = np.array(X_train)
samples_x_train = np.array(samples_x_train)

print(samples_x_train)
print(X_train)


['9597' '9143' '8967' ... '1954' '9707' '6120']
[['G' 'G' 'G' ... '?' 'T' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'A']
 ['A' 'G' 'A' ... 'A' '?' 'A']
 ...
 ['G' 'A' 'G' ... 'T' 'T' 'A']
 ['G' 'G' 'A' ... 'A' 'T' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'C']]


In [9]:
# Read phenotype values

y_train = []
samples_y_train = []

f = open("phenotype_values.csv","r")

for i,line in enumerate(f):
    if(i == 0):
        continue
    sv = line.strip().split(",")
    samples_y_train.append(sv[0])
    y_train.append(float(sv[1]))
    
f.close()

y_train = np.array(y_train)
samples_y_train = np.array(samples_y_train)

print (samples_y_train)
print (y_train)

['9608' '9801' '9647' ... '9894' '6200' '9917']
[53.43 58.81 53.57 ... 53.68 54.62 53.35]


In [10]:
X_test = []
samples_x_test=[]

fd=open("unknown_genotypes.csv","r")

for i, line in enumerate(fd):
    if(i==0):
        continue
    sv=line.strip().split(",")
    samples_x_test.append(sv[0])
    row=[]
    
    for element in sv[1:]:
        row.append(element)
    X_test.append(row)
    
fd.close()
X_test=np.array(X_test)
samples_x_test=np.array(samples_x_test)
print(samples_x_test)
print(X_test)


['9419' '5913' '9953' '210' '1652' '1247' '9968' '6021' '7504' '8389'
 '9436' '8132' '1722' '7250' '7' '6197' '9602' '9737' '126' '9615' '9846'
 '9945' '5959' '9844' '9769' '5394' '7570' '5811' '2240' '5871' '9722'
 '895' '386' '2320' '9638' '9766' '544' '6192' '7213' '1404' '506' '338'
 '504' '9113' '7123' '7262' '9813' '4826' '7256' '5799' '9651' '7391'
 '9739' '5628' '8037' '340' '7298' '8337' '8218' '5760' '7073' '957'
 '1158' '1612' '9748' '9816' '9511' '7210' '5860' '1862' '5795' '6919'
 '9869' '60' '8608' '7524' '5202' '424' '2166' '9529' '9588' '8247' '1006'
 '7578' '5961' '9888' '10022' '9759' '9718' '5812' '203' '7347' '7413'
 '9909' '6918' '9353' '9386' '6092' '9728' '9927' '6110' '6237' '9672'
 '9007' '8237' '9749' '6427' '9827' '2057' '9717' '9991' '1829' '9772'
 '9973' '2370' '9885' '1363' '7479' '5722' '9321' '6046' '15591' '6126'
 '5159' '6241' '5856' '9828' '9567' '7217' '8' '8230' '5923' '5276' '5821'
 '6946' '9690' '7209' '148' '7343' '9391' '7078' '7079' '9860' '743

In [11]:
#Replace "?" with np.nan
X_train = np.where(X_train == "?", np.nan, X_train)
X_test = np.where(X_test == "?", np.nan, X_test)

print(X_test, X_train)

[['G' 'G' 'G' ... 'T' 'T' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'A']
 ['G' 'G' 'G' ... 'T' 'T' 'A']
 ...
 ['nan' 'G' 'G' ... 'T' 'C' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'A']
 ['A' 'G' 'G' ... 'T' 'C' 'A']] [['G' 'G' 'G' ... 'nan' 'T' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'A']
 ['A' 'G' 'A' ... 'A' 'nan' 'A']
 ...
 ['G' 'A' 'G' ... 'T' 'T' 'A']
 ['G' 'G' 'A' ... 'A' 'T' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'C']]


In [12]:
#Encode nucleotide values

for j in range (X_train.shape[1]):
    
    values, counts = np.unique(X_train[:,j], return_counts=True)
    values=values[:2]
    counts=counts[:2]

    X_train[:,j] = np.where(X_train[:,j] == values[np.argmax(counts)], 0, X_train[:,j])
    X_train[:,j] = np.where(X_train[:,j] == values[np.argmin(counts)], 2, X_train[:,j])
    #X_train[:,j] = np.where(X_train[:,j] == 'nan', np.nan, X_train[:,j])

for j in range (X_test.shape[1]):
    
    values, counts = np.unique(X_test[:,j], return_counts=True)
    
    values=values[:2]
    counts=counts[:2]
    
    X_test[:,j] = np.where(X_test[:,j] == values[np.argmax(counts)], 0, X_test[:,j])
    X_test[:,j] = np.where(X_test[:,j] == values[np.argmin(counts)], 2, X_test[:,j])
    X_test[:,j] = np.where(values[np.argmax(counts)]==values[np.argmin(counts)], 2, X_test[:,j])
    
    #X_test[:,j] = np.where(X_test[:,j] == 'nan', np.nan, X_test[:,j])
#Convert array from string to float
X_train = X_train.astype(np.float_)
X_test = X_test.astype(np.float_)

print(X_train,X_test)
    

[[ 0.  0.  0. ... nan  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 2.  0.  2. ...  0. nan  0.]
 ...
 [ 0.  2.  0. ...  2.  0.  0.]
 [ 0.  0.  2. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  2.]] [[ 0.  0.  0. ...  2.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  2.  0.  0.]
 ...
 [nan  0.  0. ...  2.  2.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 2.  0.  0. ...  2.  2.  0.]]


In [13]:
# General analysis data:

print("No Samples:\t\t %d" % X_train.shape[0])
print("No Features:\t\t %d" % X_train.shape[1])

missing_train = ((np.isnan(X_train)).sum()/X_train.size*100)
print("X_train Missing Values:\t\t %.2f%%" % missing_train)

missing_test = ((np.isnan(X_test)).sum()/X_test.size*100)
print("X_test Missing Values:\t\t %.2f%%" % missing_test)

No Samples:		 1826
No Features:		 5000
X_train Missing Values:		 10.00%
X_test Missing Values:		 10.01%


In [15]:
# Assess missing values per sample


sample_indices_to_remove = []
for i in range(X_train.shape[0]):
    missing = np.isnan(X_train[i,:]).sum()/X_train.shape[1]*100
    if missing>50:
        print("Sample %d has %.2f missing values" % (i,missing))
        sample_indices_to_remove.append(i)

if (len(sample_indices_to_remove) == 0):
    print("All samples have less than 50 % missing values")

All samples have less than 50 % missing values


In [16]:
# Match genotypes with phenotype values
truth_table = (samples_x_train[:,np.newaxis]==samples_y_train)
ind = np.where(truth_table==True)

samples_x_train = samples_x_train[ind[0]]
samples_y_train = samples_y_train[ind[1]]

X_train = X_train[ind[0],:]
y_train = y_train[ind[1]]

print("No Samples X:\t\t%d" % X_train.shape[0])
print("No Samples y:\t\t%d" % y_train.shape[0])

print("Samples correct order:\t" + str(np.any(samples_x_train==samples_y_train)))


No Samples X:		1826
No Samples y:		1826
Samples correct order:	True


In [17]:
# Impute missing values on training data

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="most_frequent")
X_train = imputer.fit_transform(X_train) 
X_test = imputer.fit_transform(X_test) 

print(X_train,X_test)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [2. 0. 2. ... 0. 0. 0.]
 ...
 [0. 2. 0. ... 2. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 2.]] [[0. 0. 0. ... 2. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 2. 0. 0.]
 ...
 [0. 0. 0. ... 2. 2. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [2. 0. 0. ... 2. 2. 0.]]


In [130]:
#standardise the data
from sklearn.preprocessing import StandardScaler 

scaler = StandardScaler()
Xn = scaler.fit_transform(X_train)

#compute the covariance matrix on the standardised data
n = Xn.shape[0]
C = 1/(n-1) * np.dot(Xn.T,Xn)

#eigendecompose the matrix  𝐂  into its eigenvalues and eigenvector
import numpy.linalg as linalg
d, V = linalg.eig(C)

#sort the eigenvalues in decreasing order, re-sort the columns of the eigenvector matrix 𝑉  using the indices from the sorting of the eigenvalues
ind = np.argsort(d)[::-1]
d = d[ind]
V = V[:,ind]

Xn1 = np.dot(Xn,V[:,0:1000])
Xn2 = np.array(Xn1,dtype=float)
print(Xn2)

#calculate how much of the total variance the PCs account for
ratios_variance_explained = d/d.sum()
va = ratios_variance_explained[0:1000].sum()


print("First 1000 PCs account for %.2f %% of the total variance!" % (va*100))

# match sample ids with x-train(1000 now) to y-train (5000 now)
import pandas as pd

df_X_train=pd.DataFrame(Xn2)
df_y_train=pd.DataFrame(y_train)
frames=[df_X_train]
df_final=pd.concat(frames, axis=1, join='inner')

#transform test data

Xn3_Xtest = np.dot(X_test,V[:,0:1000])
Xn4_Xtest = np.array(Xn3_Xtest,dtype=float)
print(Xn4_Xtest)



C:\Users\zhang\AppData\Local\Temp/ipykernel_19996/2597743246.py:21: ComplexWarning: Casting complex values to real discards the imaginary part
  Xn2 = np.array(Xn1,dtype=float)


[[-8.68376349e+00 -5.60131328e+00  9.34610142e+00 -7.22363310e+00
   3.55675390e+00 -1.84870475e+00 -3.74926545e+00  9.68223168e-01
  -5.15176093e+00  6.59121316e+00 -1.74074725e+00 -6.47479824e+00
   2.60862688e+00 -2.43777384e-01 -3.29074488e+00 -2.77472067e+00
  -4.76311867e-01 -3.20497586e+00  6.40906693e-01  1.08835736e+00
  -1.02659332e+01 -3.03039887e+00 -1.88475580e+00 -1.07079411e+00
  -2.28698591e+00 -9.52647753e-01  5.58483797e-01  2.11235683e+00
   1.49084209e+00  1.65488968e+00 -5.81795017e-01 -2.96281599e+00
   1.47569798e+00 -7.56056610e-01 -1.16482010e+00 -2.67859291e-02
  -1.74370616e+00  2.23327691e+00  3.23429204e+00  8.76098805e-01
  -3.47589101e-02  3.84258978e-01  6.09368290e+00 -6.21505760e+00
   1.40437972e+00 -1.50421052e+00 -4.00868908e+00 -3.77425532e-01
   1.38139563e-01 -2.66724948e+00 -3.59302946e+00 -5.90826728e-01
   1.38880614e+00 -1.89886394e+00  2.28210283e+00 -2.18326640e+00
   3.31345279e-01  1.09102915e+00  2.65242169e-01  1.08360669e+00
   4.31982

C:\Users\zhang\AppData\Local\Temp/ipykernel_19996/2597743246.py:29: ComplexWarning: Casting complex values to real discards the imaginary part
  print("First 1000 PCs account for %.2f %% of the total variance!" % (va*100))
C:\Users\zhang\AppData\Local\Temp/ipykernel_19996/2597743246.py:42: ComplexWarning: Casting complex values to real discards the imaginary part
  Xn4_Xtest = np.array(Xn3_Xtest,dtype=float)


[[ 1.17118393e+00 -5.57417216e-01 -3.12501580e+00  5.96970394e+00
  -1.16032838e+01 -2.43285826e+00  1.45045871e+00 -2.98707490e+00
   3.58998963e+00  2.40435755e+00  9.11702505e-01  1.39231109e+00
  -2.81237861e+00  6.67188169e-01 -1.84900900e+00  1.94124519e-01
  -1.94944489e+00 -1.70471361e-01  2.08862952e+00  9.84127994e-01
  -2.01896040e+00 -7.74635561e-02  1.11959510e+00  2.03871192e+00
  -1.53205346e+00 -1.45569406e+00  4.58555186e-01  1.74246942e+00
   8.71371734e-01  8.43721904e-01 -1.72015981e-01 -7.03308694e-01
  -2.42546221e-01  1.86286086e+00  2.88972862e-02  1.74746202e-01
  -2.64466350e-01  7.58290958e-01  1.16642788e-01  1.07503843e+00
  -1.10438296e+00  8.45346058e-01  6.92157631e-01 -4.74250800e-01
  -1.47365595e+00  1.29692452e+00 -3.88121730e-01 -1.15111438e+00
  -8.36498994e-01 -4.61080542e-01 -7.85474052e-01  3.74638228e-01
  -2.10253112e-01 -1.49916374e+00  1.22717631e+00  1.12248073e-01
  -2.31705366e+00 -1.10198436e+00 -1.98091767e+00 -2.48760763e+00
  -3.27228

In [ ]:
#importing required libraries
import pylab as pl
import numpy as np

pl.figure(figsize=(14,6))

#plot variance for the first 1000 features
n=1000

ax = pl.subplot(111)
ax.bar(np.arange(1,1+len(ratios_variance_explained[0:1000])),ratios_variance_explained[0:1000]*100)
ax.plot(np.arange(1,1+len(ratios_variance_explained[0:1000])), np.cumsum(ratios_variance_explained[0:1000])*100,color="tab:green", label="Cumulative Variance Explained")
ax.set_xticks([1,100,1000])
ax.set_yticks([10,20,30,40,50,60,70,80,90,100])
pl.axhline(90,color="tab:orange",linestyle="dashed",label="90% Threshold")

ax.grid(color="#CCCCCC")
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.set_xlabel("Principal Components")
ax.set_ylabel("Total Variance in %")
pl.legend()
pl.tight_layout()

import matplotlib.pyplot as plt
plt.savefig('PCA.png')


In [ ]:
#plot variance for the first 100 features(zoomed in)
n=100

ax = pl.subplot(111)
ax.bar(np.arange(1,1+len(ratios_variance_explained[0:100])),ratios_variance_explained[0:100]*100)
ax.plot(np.arange(1,1+len(ratios_variance_explained[0:100])), np.cumsum(ratios_variance_explained[0:100])*100,color="tab:green", label="Cumulative Variance Explained")
ax.set_xticks([1,10,100])
ax.set_yticks([10,20,30,40,50,60,70,80,90,100])
pl.axhline(90,color="tab:orange",linestyle="dashed",label="90% Threshold")

ax.grid(color="#CCCCCC")
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.set_xlabel("Principal Components")
ax.set_ylabel("Total Variance in %")
pl.legend()
pl.tight_layout()

import matplotlib.pyplot as plt
plt.savefig('PCA_100.png')

In [136]:
from sklearn import linear_model
model2=linear_model.Ridge(alpha=5000)
model2.fit(Xn2, df_y_train)
y_predictions_training = model2.predict(Xn2)
y_predictions_testing = model2.predict(Xn4_Xtest)

print("MSE (Train):\t%.2f" % metrics.mean_squared_error(y_train, y_predictions_training))
print("R2 (Train):\t%.2f" % metrics.r2_score(y_train,y_predictions_training))
print("MSE (Train):\t%.2f" % metrics.mean_squared_error(y_train, y_predictions_training))

# Calculation of Explained Variance
from sklearn.model_selection import cross_val_score
EV = cross_val_score(model2, Xn2, y_train, cv=10, scoring="explained_variance").mean()
print("EV (Train):\t%.2f" % EV)

MSE (Train):	2.10
R2 (Train):	0.80
MSE (Train):	2.10
EV (Train):	0.58


In [73]:
from sklearn import linear_model

model3=linear_model.ElasticNet(alpha=0.13135893963030046,l1_ratio=0.09)
model3.fit(Xn2, df_y_train)
y_predictions_training = model3.predict(Xn2)
y_predictions_testing = model3.predict(Xn4_Xtest)

#CV because the parameter values are pre-determined



from sklearn.linear_model import ElasticNet
from sklearn.datasets import make_regression

Xn2, df_y_train = make_regression(n_features=1000, random_state=0)
regr = ElasticNet(random_state=0)
regr.fit(Xn2, df_y_train)
ElasticNet(random_state=0)
print(regr.coef_)
print(regr.intercept_)
print(regr.predict())


In [74]:

from sklearn import metrics

print("MSE (Train):\t%.2f" % metrics.mean_squared_error(y_train, y_predictions_training))
print("EV (Train):\t %.2f" %metrics.explained_variance_score(y_train,y_predictions_training))
print("MAE (Train):\t %.2f" %metrics.mean_absolute_error(y_train, y_predictions_training))
print("R2 (Train):\t%.2f" % metrics.r2_score(y_train, y_predictions_training))

#The metrics have to be computed by the server(ys)
'''
print("MSE (Test):\t%.2f" % metrics.mean_squared_error(y_test, y_predictions_testing))
print("EV (Test): \t %.2f" %metrics.explained_variance_score(y_test,y_predictions_testing))
print("MAE (Test):\t %.2f" %metrics.mean_absolute_error(y_test, y_predictions_testing))
print("R2 (Test):\t%.2f" % metrics.r2_score(y_test, y_predictions_testing))
'''
#If the error of the predictor is unbiased, EV and R^2 scores are the same.

MSE (Train):	1.18
EV (Train):	 0.89
MAE (Train):	 0.85
R2 (Train):	0.89


'\nprint("MSE (Test):\t%.2f" % metrics.mean_squared_error(y_test, y_predictions_testing))\nprint("EV (Test): \t %.2f" %metrics.explained_variance_score(y_test,y_predictions_testing))\nprint("MAE (Test):\t %.2f" %metrics.mean_absolute_error(y_test, y_predictions_testing))\nprint("R2 (Test):\t%.2f" % metrics.r2_score(y_test, y_predictions_testing))\n'

In [126]:
import pandas as pd
#print(y_predictions_testing)

f=open("y_predictions_PCA3.csv","w")

for elem in y_predictions_testing:
    f.write(str(elem)+"\n")
    
f.close()


import pandas as pd
df1 = pd.read_csv("unknown_genotypes.csv", usecols = ['sample_ids'])
print(df1)
df2 = pd.read_csv("y_predictions_PCA3.csv",header=None)
print(df2)
df1_1 = pd.DataFrame(df1)
df2_1 = pd.DataFrame(df2)

frames = [df1_1,df2_1]
df_final=pd.concat(frames, axis=1, join='inner')

df_final.to_csv("y_predictions_PCA4.csv",index=False,header=False)

     sample_ids
0          9419
1          5913
2          9953
3           210
4          1652
..          ...
198        5253
199        7317
200        1744
201        9812
202         867

[203 rows x 1 columns]
             0
0    54.002287
1    54.808714
2    57.148852
3    55.909101
4    60.409843
..         ...
198  53.866888
199  54.308237
200  60.395578
201  57.298655
202  60.591333

[203 rows x 1 columns]


In [89]:
np.set_printoptions(edgeitems=127)
#print(model1.intercept_,model1.coef_)
#print(model2.intercept_,model2.coef_)
print(model3.intercept_,model3.coef_[model3.coef_!=0].size,model3.coef_)

[54.57643483] 896 [ 7.91914513e-02 -1.06584855e-02 -8.12616199e-03 -2.89928073e-02
  3.38741929e-03 -2.14280621e-02  2.67408235e-02 -1.27495521e-02
  4.33225419e-02  5.79048530e-02 -6.08970855e-02  4.97000117e-02
 -5.89500497e-04 -8.86097675e-04 -5.44003782e-03 -2.23483043e-02
  8.83289778e-03 -6.77820200e-02  3.72120449e-02 -3.31714857e-03
  2.25397082e-02  7.40684768e-02 -3.27716556e-02  2.44762667e-02
 -3.07334258e-02  2.03952586e-02 -6.43067315e-03  2.57582561e-02
 -5.10922949e-02  3.90522213e-02 -6.81105710e-02 -3.62893839e-02
 -3.00337974e-02 -1.40178631e-02 -1.81285222e-02  2.87800722e-02
  1.14289597e-02 -3.23580933e-02 -4.34528357e-02 -3.59361436e-02
  1.45611868e-02  4.50079737e-02  3.88108245e-03  3.24223793e-02
 -1.96078764e-02 -2.06566467e-02 -2.92374674e-02 -5.74422056e-02
 -6.28267906e-02  3.41371963e-02  3.46230187e-02 -7.68839745e-02
 -5.32644573e-02 -3.75650198e-02 -3.35260630e-02 -3.26317871e-02
  2.77376056e-02 -2.65396770e-02  1.02739721e-02  2.43274809e-02
 -5.561