In [96]:
%matplotlib inline
import pylab as pl
import numpy as np
import pandas as pd

#Read data

X_train = []
samples_x_train = []

f = open("genotypes.csv","r")

for i,line in enumerate(f):
    if(i == 0):
        continue
    
    sv = line.strip().split(",")
    samples_x_train.append(sv[0])
    
    row = []
    for element in sv[1:]:
        row.append(element)
    X_train.append(row)
    
f.close()

X_train = np.array(X_train)
samples_x_train = np.array(samples_x_train)

print(samples_x_train)
print(X_train)


['9597' '9143' '8967' ... '1954' '9707' '6120']
[['G' 'G' 'G' ... '?' 'T' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'A']
 ['A' 'G' 'A' ... 'A' '?' 'A']
 ...
 ['G' 'A' 'G' ... 'T' 'T' 'A']
 ['G' 'G' 'A' ... 'A' 'T' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'C']]


In [97]:
# Read phenotype values

y_train = []
samples_y_train = []

f = open("phenotype_values.csv","r")

for i,line in enumerate(f):
    if(i == 0):
        continue
    sv = line.strip().split(",")
    samples_y_train.append(sv[0])
    y_train.append(float(sv[1]))
    
f.close()

y_train = np.array(y_train)
samples_y_train = np.array(samples_y_train)

print (samples_y_train)
print (y_train)

['9608' '9801' '9647' ... '9894' '6200' '9917']
[53.43 58.81 53.57 ... 53.68 54.62 53.35]


In [98]:
X_test = []
samples_x_test=[]

fd=open("unknown_genotypes.csv","r")

for i, line in enumerate(fd):
    if(i==0):
        continue
    sv=line.strip().split(",")
    samples_x_test.append(sv[0])
    row=[]
    
    for element in sv[1:]:
        row.append(element)
    X_test.append(row)
    
fd.close()
X_test=np.array(X_test)
samples_x_test=np.array(samples_x_test)
print(samples_x_test)
print(X_test)


['9419' '5913' '9953' '210' '1652' '1247' '9968' '6021' '7504' '8389'
 '9436' '8132' '1722' '7250' '7' '6197' '9602' '9737' '126' '9615' '9846'
 '9945' '5959' '9844' '9769' '5394' '7570' '5811' '2240' '5871' '9722'
 '895' '386' '2320' '9638' '9766' '544' '6192' '7213' '1404' '506' '338'
 '504' '9113' '7123' '7262' '9813' '4826' '7256' '5799' '9651' '7391'
 '9739' '5628' '8037' '340' '7298' '8337' '8218' '5760' '7073' '957'
 '1158' '1612' '9748' '9816' '9511' '7210' '5860' '1862' '5795' '6919'
 '9869' '60' '8608' '7524' '5202' '424' '2166' '9529' '9588' '8247' '1006'
 '7578' '5961' '9888' '10022' '9759' '9718' '5812' '203' '7347' '7413'
 '9909' '6918' '9353' '9386' '6092' '9728' '9927' '6110' '6237' '9672'
 '9007' '8237' '9749' '6427' '9827' '2057' '9717' '9991' '1829' '9772'
 '9973' '2370' '9885' '1363' '7479' '5722' '9321' '6046' '15591' '6126'
 '5159' '6241' '5856' '9828' '9567' '7217' '8' '8230' '5923' '5276' '5821'
 '6946' '9690' '7209' '148' '7343' '9391' '7078' '7079' '9860' '743

In [99]:
#Replace "?" with np.nan
X_train = np.where(X_train == "?", np.nan, X_train)
X_test = np.where(X_test == "?", np.nan, X_test)

print(X_test, X_train)

[['G' 'G' 'G' ... 'T' 'T' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'A']
 ['G' 'G' 'G' ... 'T' 'T' 'A']
 ...
 ['nan' 'G' 'G' ... 'T' 'C' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'A']
 ['A' 'G' 'G' ... 'T' 'C' 'A']] [['G' 'G' 'G' ... 'nan' 'T' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'A']
 ['A' 'G' 'A' ... 'A' 'nan' 'A']
 ...
 ['G' 'A' 'G' ... 'T' 'T' 'A']
 ['G' 'G' 'A' ... 'A' 'T' 'A']
 ['G' 'G' 'G' ... 'A' 'T' 'C']]


In [100]:
#Encode nucleotide values

for j in range (X_train.shape[1]):
    
    values, counts = np.unique(X_train[:,j], return_counts=True)
    values=values[:2]
    counts=counts[:2]

    X_train[:,j] = np.where(X_train[:,j] == values[np.argmax(counts)], 0, X_train[:,j])
    X_train[:,j] = np.where(X_train[:,j] == values[np.argmin(counts)], 2, X_train[:,j])
    #X_train[:,j] = np.where(X_train[:,j] == 'nan', np.nan, X_train[:,j])

for j in range (X_test.shape[1]):
    
    values, counts = np.unique(X_test[:,j], return_counts=True)
    
    values=values[:2]
    counts=counts[:2]
    
    X_test[:,j] = np.where(X_test[:,j] == values[np.argmax(counts)], 0, X_test[:,j])
    X_test[:,j] = np.where(X_test[:,j] == values[np.argmin(counts)], 2, X_test[:,j])
    X_test[:,j] = np.where(values[np.argmax(counts)]==values[np.argmin(counts)], 2, X_test[:,j])
    
    #X_test[:,j] = np.where(X_test[:,j] == 'nan', np.nan, X_test[:,j])
#Convert array from string to float
X_train = X_train.astype(np.float_)
X_test = X_test.astype(np.float_)

print(X_train,X_test)
    

[[ 0.  0.  0. ... nan  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 2.  0.  2. ...  0. nan  0.]
 ...
 [ 0.  2.  0. ...  2.  0.  0.]
 [ 0.  0.  2. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  2.]] [[ 0.  0.  0. ...  2.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  2.  0.  0.]
 ...
 [nan  0.  0. ...  2.  2.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 2.  0.  0. ...  2.  2.  0.]]


In [102]:
# General analysis data:

print("No Samples:\t\t %d" % X_train.shape[0])
print("No Features:\t\t %d" % X_train.shape[1])

missing_train = ((np.isnan(X_train)).sum()/X_train.size*100)
print("X_train Missing Values:\t\t %.2f%%" % missing_train)

missing_test = ((np.isnan(X_test)).sum()/X_test.size*100)
print("X_test Missing Values:\t\t %.2f%%" % missing_test)

No Samples:		 1826
No Features:		 5000
X_train Missing Values:		 10.00%
X_test Missing Values:		 10.01%


In [8]:
# Assess missing values per sample


sample_indices_to_remove = []
for i in range(X.shape[0]):
    missing = np.isnan(X[i,:]).sum()/X.shape[1]*100
    if missing>50:
        print("Sample %d has %.2f missing values" % (i,missing))
        sample_indices_to_remove.append(i)

if (len(sample_indices_to_remove) == 0):
    print("All samples have less than 50 % missing values")

All samples have less than 50 % missing values


In [103]:
# Match genotypes with phenotype values
truth_table = (samples_x_train[:,np.newaxis]==samples_y_train)
ind = np.where(truth_table==True)

samples_x_train = samples_x_train[ind[0]]
samples_y_train = samples_y_train[ind[1]]

X_train = X_train[ind[0],:]
y_train = y_train[ind[1]]

print("No Samples X:\t\t%d" % X_train.shape[0])
print("No Samples y:\t\t%d" % y_train.shape[0])

print("Samples correct order:\t" + str(np.any(samples_x_train==samples_y_train)))


No Samples X:		1826
No Samples y:		1826
Samples correct order:	True


In [104]:
# Impute missing values on training data

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="most_frequent")
X_train = imputer.fit_transform(X_train) 
X_test = imputer.fit_transform(X_test) 

print(X_train,X_test)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [2. 0. 2. ... 0. 0. 0.]
 ...
 [0. 2. 0. ... 2. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 2.]] [[0. 0. 0. ... 2. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 2. 0. 0.]
 ...
 [0. 0. 0. ... 2. 2. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [2. 0. 0. ... 2. 2. 0.]]


In [35]:
'''
from sklearn import linear_model
model2=linear_model.Ridge(alpha=5000)
model2.fit(X_train, y_train)
predictions_training = model2.predict(X_train)
predictions_testing = model2.predict(X_test)

print("MSE (Train):\t%.2f" % metrics.mean_squared_error(y_train, predictions_training))
print("R2 (Train):\t%.2f" % metrics.r2_score(y_train, predictions_training))
print("MSE (Test):\t%.2f" % metrics.mean_squared_error(y_test, predictions_testing))
print("R2 (Test):\t%.2f" % metrics.r2_score(y_test, predictions_testing))
'''

MSE (Train):	2.80
R2 (Train):	0.74
MSE (Test):	4.50
R2 (Test):	0.49


In [105]:
from sklearn import linear_model




model3=linear_model.ElasticNet(alpha=0.13135893963030046,l1_ratio=0.09,max_iter=7000)
model3.fit(X_train, y_train)
y_predictions_training = model3.predict(X_train)
y_predictions_testing = model3.predict(X_test)





NameError: name 'metrics' is not defined

In [106]:
from sklearn import metrics

print("MSE (Train):\t%.2f" % metrics.mean_squared_error(y_train, y_predictions_training))
print("EV (Train):\t %.2f" %metrics.explained_variance_score(y_train,y_predictions_training))
print("MAE (Train):\t %.2f" %metrics.mean_absolute_error(y_train, y_predictions_training))
print("R2 (Train):\t%.2f" % metrics.r2_score(y_train, y_predictions_training))

#Thes metrics have to be computed by the server
'''
print("MSE (Test):\t%.2f" % metrics.mean_squared_error(y_test, y_predictions_testing))
print("EV (Test): \t %.2f" %metrics.explained_variance_score(y_test,y_predictions_testing))
print("MAE (Test):\t %.2f" %metrics.mean_absolute_error(y_test, y_predictions_testing))
print("R2 (Test):\t%.2f" % metrics.r2_score(y_test, y_predictions_testing))
'''

MSE (Train):	0.82
EV (Train):	 0.92
MAE (Train):	 0.71
R2 (Train):	0.92


NameError: name 'y_test' is not defined

In [139]:
import pandas as pd

df_samples=pd.DataFrame(samples_x_test)
df_y_pred=pd.DataFrame(y_predictions_testing)
frames=[df_samples,df_y_pred]
df_final=pd.concat(frames, axis=1, join='inner')

df_final.to_csv("y_predictions.csv",index=False,header=False)

In [111]:
np.set_printoptions(edgeitems=127)
#print(model1.intercept_,model1.coef_)
#print(model2.intercept_,model2.coef_)
print(model3.intercept_,model3.coef_[model3.coef_!=0].size,model3.coef_)

51.94729974473867 1726 [ 0.00000000e+00 -1.26403277e-02  0.00000000e+00 -0.00000000e+00
  0.00000000e+00 -0.00000000e+00  4.59877878e-02  1.74819276e-02
  0.00000000e+00 -4.16598871e-03  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  2.33003331e-02 -8.67336744e-03 -0.00000000e+00
 -0.00000000e+00  3.00966527e-02 -0.00000000e+00  0.00000000e+00
 -8.43151412e-03  4.87532209e-02 -0.00000000e+00  4.67429208e-03
 -0.00000000e+00  1.17282141e-02  5.30281563e-03 -0.00000000e+00
  0.00000000e+00  5.85337213e-03 -0.00000000e+00  5.54044703e-03
  0.00000000e+00 -0.00000000e+00  1.86337760e-02  8.70225884e-02
 -0.00000000e+00  8.32665335e-02 -0.00000000e+00 -6.66674319e-03
  0.00000000e+00 -0.00000000e+00  3.51947267e-02  5.90958410e-02
 -2.24420727e-02  7.20178684e-03 -1.45471883e-02 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.02659529e-02
  

In [18]:
from sklearn.model_selection import cross_val_score

print(cross_val_score(model3, x, y, cv=10, scoring="explained_variance").mean())

NameError: name 'model3' is not defined